spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/result_manager
    username: postgres
    password: PostgreSql@2601
    driver-class_name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
